// import "./globals.css";
// import { Varela_Round,Outfit } from 'next/font/google'
// import SpotlightWrapper from "@/components/animations/SpotlightWrapper";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import { ThemeProvider } from "@/components/ThemeProvider";

// const varelaRound = Varela_Round({
//   weight: '400',
//   subsets: ['latin'],
//   display: 'swap',
// });
// const outFit = Outfit({
//   subsets:['latin'],
//   weight:["400","600","800"],
// })

// export const metadata = {
//   title: "Portfolio",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${varelaRound.className} ${outFit.className} flex flex-col min-h-screen justify-between ` }>
//       <ThemeProvider>
//         <SpotlightWrapper
//        className="custom-spotlight-card w-full" spotlightColor="rgba(130, 29, 255, 0.01)"
//        > <Navbar/>
//        {/* rgba(0, 229, 255, 0.25)*/}
     
//         {/* 0, 229, 255, 0.35 */}
//         {/* 100, 255, 150, 0.5 */}
//          {children}
//          <Footer/>
//        </SpotlightWrapper>
//        </ThemeProvider>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { Varela_Round, Outfit } from 'next/font/google'
import SpotlightWrapper from "@/components/animations/SpotlightWrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";

const varelaRound = Varela_Round({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});
const outFit = Outfit({
  subsets:['latin'],
  weight:["400","600","800"],
})

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${varelaRound.className} ${outFit.className} flex flex-col min-h-screen justify-between`}>
      <ThemeProvider>
        <SpotlightWrapper
       className="custom-spotlight-card w-full" spotlightColor="rgba(130, 29, 255, 0.01)"
       > <Navbar/>
         {children}
         <Footer/>
       </SpotlightWrapper>
       </ThemeProvider>
      </body>
    </html>
  );
}