import "./globals.css";
import { Varela_Round,Outfit } from 'next/font/google'
import SpotlightWrapper from "@/components/animations/SpotlightWrapper";
import Navbar from "@/components/Navbar";


const varelaRound = Varela_Round({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});
const outFit = Outfit({
  subsets:['latin'],
  weight:["400","600","800"],
})

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${varelaRound.className} ${outFit.className}` }>
          <Navbar/>
        <SpotlightWrapper
       className="custom-spotlight-card w-full" spotlightColor="rgba(0, 229, 255, 0.4)"
       >
         {children}
       </SpotlightWrapper>
         
      </body>
    </html>
  );
}
